// Data for Evid Wijaya portfolio - static content from LinkedIn/resume
// Translated into EN, ID, ZH

export const PROFILE = {
  en: {
    name: 'Evid Wijaya',
    title: 'Information Systems Student · Graphic Designer · Cloud Computing Enthusiast',
    bio: 'A final-year Information Systems student at the School of Technopreneur Nusantara, currently contributing as a Graphic Designer at Star Champs Indonesia. Combines academic knowledge with professional experience to create impactful designs for social media, e-commerce, and promotional materials. Recently enhanced cloud computing expertise through Bangkit Academy, gaining skills in Google Cloud Platform.',
    location: 'Kota Tangerang, Banten, Indonesia',
    email: 'evidwijaya@gmail.com',
    linkedin: 'https://www.linkedin.com/in/evid-wijaya',
    github: 'https://github.com/Eugenewijaya',
    portfolio: 'https://sites.google.com/view/evidwijaya/',
    avatar: '/avatar.png',
    skills: ['HTML', 'Project Management', 'Programming', 'Graphic Design', 'Video Editing', 'Cloud Computing', 'Google Cloud Platform', 'Canva', 'CapCut', 'Meta Business Suite'],
  },
  id: {
    name: 'Evid Wijaya',
    title: 'Mahasiswa Sistem Informasi · Desainer Grafis · Penggiat Cloud Computing',
    bio: 'Mahasiswa tingkat akhir Sistem Informasi di School of Technopreneur Nusantara, yang lagi sibuk bantu-bantu sebagai Graphic Designer di Star Champs Indonesia. Suka banget gabungin ilmu kuliah sama pengalaman kerja buat bikin desain yang asik dan berdampak buat sosmed, e-commerce, dan bahan promosi. Baru aja kelar ikut Bangkit Academy buat nambah ilmu Cloud Computing, dapet banyak skill seru soal Google Cloud Platform.',
    location: 'Kota Tangerang, Banten, Indonesia',
    email: 'evidwijaya@gmail.com',
    linkedin: 'https://www.linkedin.com/in/evid-wijaya',
    github: 'https://github.com/Eugenewijaya',
    portfolio: 'https://sites.google.com/view/evidwijaya/',
    avatar: '/avatar.png',
    skills: ['HTML', 'Manajemen Proyek', 'Pemrograman', 'Desain Grafis', 'Edit Video', 'Cloud Computing', 'Google Cloud Platform', 'Canva', 'CapCut', 'Meta Business Suite'],
  },
  zh: {
    name: 'Evid Wijaya',
    title: '信息系统学生 · 平面设计师 · 云计算爱好者',
    bio: 'Nusantara科技创业学院信息系统专业大四学生，目前在Star Champs Indonesia担任平面设计师。将学术知识与专业经验相结合，为社交媒体、电子商务和宣传材料创作具有影响力的设计。最近通过Bangkit Academy提升了云计算专业技能，掌握了谷歌云平台的相关技术。',
    location: '印度尼西亚，万丹省，坦格朗市',
    email: 'evidwijaya@gmail.com',
    linkedin: 'https://www.linkedin.com/in/evid-wijaya',
    github: 'https://github.com/Eugenewijaya',
    portfolio: 'https://sites.google.com/view/evidwijaya/',
    avatar: '/avatar.png',
    skills: ['HTML', '项目管理', '编程', '平面设计', '视频剪辑', '云计算', '谷歌云平台 (GCP)', 'Canva', 'CapCut', 'Meta Business Suite'],
  }
}

export const CERTIFICATIONS = {
  en: [
    { name: 'Implement Load Balancing on Compute Engine', issuer: 'Google Cloud', color: '#4285F4' },
    { name: 'Google Cloud Computing Foundations: Infrastructure in Google Cloud', issuer: 'Google Cloud', color: '#34A853' },
    { name: 'Develop your Google Cloud Network', issuer: 'Google Cloud', color: '#FBBC05' },
    { name: 'Build a Secure Google Cloud Network', issuer: 'Google Cloud', color: '#EA4335' },
    { name: 'Video Content Creator Batch 2 2022', issuer: 'KOMINFO & EFFION Creator School', color: '#6366f1' },
  ],
  id: [
    { name: 'Implement Load Balancing on Compute Engine', issuer: 'Google Cloud', color: '#4285F4' },
    { name: 'Google Cloud Computing Foundations: Infrastructure in Google Cloud', issuer: 'Google Cloud', color: '#34A853' },
    { name: 'Develop your Google Cloud Network', issuer: 'Google Cloud', color: '#FBBC05' },
    { name: 'Build a Secure Google Cloud Network', issuer: 'Google Cloud', color: '#EA4335' },
    { name: 'Video Content Creator Batch 2 2022', issuer: 'KOMINFO & EFFION Creator School', color: '#6366f1' },
  ],
  zh: [
    { name: '在计算引擎上实现负载均衡', issuer: 'Google Cloud', color: '#4285F4' },
    { name: '谷歌云计算基础：基础设施', issuer: 'Google Cloud', color: '#34A853' },
    { name: '开发您的谷歌云网络', issuer: 'Google Cloud', color: '#FBBC05' },
    { name: '构建安全的谷歌云网络', issuer: 'Google Cloud', color: '#EA4335' },
    { name: '视频内容创作者第2期 (2022)', issuer: '印尼通信部 & EFFION', color: '#6366f1' },
  ]
}

export const EXPERIENCE = {
  en: [
    {
      role: 'Graphic Designer',
      company: 'Star Champs Indonesia',
      period: 'Jul 2025 – Present',
      location: 'Tangerang',
      type: 'Full-time',
      highlights: [
        '200+ digital & print designs for branding, marketing, and campaigns',
        '200% increase in social media growth within one year',
        'Managed digital campaigns via Meta Business Suite',
        'Led "The Journey of Hope" Seminar (100+ participants)',
        'Developed TheraCare – integrated therapy center information system',
      ],
      color: '#6366f1',
    },
    {
      role: 'Commissioner',
      company: 'Sagara Karya Kreanusati',
      period: 'Jan 2024 – Jul 2026',
      location: 'Indonesia',
      type: 'Agency',
      highlights: [
        'Multidisciplinary creative agency across advertising, events, and technology',
        'Empowering creativity across the Nusa Archipelago',
      ],
      color: '#8b5cf6',
    },
    {
      role: 'Cloud Computing Cohort',
      company: 'Bangkit Academy',
      period: 'Sep 2024 – Jan 2025',
      location: 'Jakarta Raya',
      type: 'Training',
      highlights: [
        'Google Cloud Platform (Compute Engine, Cloud Storage, App Engine)',
        'Cloud infrastructure, serverless computing, deployment pipelines',
        'Cross-disciplinary teamwork with ML & Mobile Dev cohorts',
      ],
      color: '#38bdf8',
    },
    {
      role: 'Graphic Designer & Video Editor',
      company: 'Freelance (Fastwork.co)',
      period: 'Sep 2023 – Jan 2025',
      location: 'Tangerang Selatan',
      type: 'Freelance',
      highlights: [
        'Brand Identity, Marketing Materials, Digital Content (Canva)',
        'Promotional & social media videos, corporate materials (CapCut)',
      ],
      color: '#f59e0b',
    },
    {
      role: 'Information System Coordinator',
      company: 'Himpunan Psikologi Indonesia (HIMPSI)',
      period: 'Aug 2024 – Dec 2024',
      location: 'Kota Tangerang',
      type: 'Volunteer',
      highlights: [
        'Built integrated registration platform on Google Sites',
        'Created e-voting system for governance decisions',
        'Managed event photography and documentation',
      ],
      color: '#10b981',
    },
  ],
  id: [
    {
      role: 'Desainer Grafis',
      company: 'Star Champs Indonesia',
      period: 'Jul 2025 – Sekarang',
      location: 'Tangerang',
      type: 'Penuh Waktu',
      highlights: [
        'Bikin 200+ desain digital & cetak buat branding, marketing, dan kampanye',
        'Ningkatin followers & growth sosmed sampai 200% dalam setahun',
        'Ngurusin kampanye digital lewat Meta Business Suite',
        'Jadi ketua panitia Seminar "The Journey of Hope" (100+ peserta)',
        'Bikin TheraCare – sistem informasi pusat terapi terintegrasi',
      ],
      color: '#6366f1',
    },
    {
      role: 'Komisaris',
      company: 'Sagara Karya Kreanusati',
      period: 'Jan 2024 – Jul 2026',
      location: 'Indonesia',
      type: 'Agensi',
      highlights: [
        'Agensi kreatif multidisiplin (periklanan, event, dan teknologi)',
        'Memberdayakan kreativitas di seluruh Nusantara',
      ],
      color: '#8b5cf6',
    },
    {
      role: 'Cloud Computing Cohort',
      company: 'Bangkit Academy',
      period: 'Sep 2024 – Jan 2025',
      location: 'Jakarta Raya',
      type: 'Pelatihan',
      highlights: [
        'Belajar Google Cloud Platform (Compute Engine, Cloud Storage, App Engine)',
        'Infrastruktur Cloud, serverless computing, deployment pipelines',
        'Kerja tim lintas disiplin bareng anak ML & Mobile Dev',
      ],
      color: '#38bdf8',
    },
    {
      role: 'Desainer Grafis & Video Editor',
      company: 'Freelance (Fastwork.co)',
      period: 'Sep 2023 – Jan 2025',
      location: 'Tangerang Selatan',
      type: 'Lepas / Freelance',
      highlights: [
        'Bikin identitas brand, materi marketing, dan konten digital (Canva)',
        'Video promosi & sosmed, materi perusahaan (CapCut)',
      ],
      color: '#f59e0b',
    },
    {
      role: 'Koordinator Sistem Informasi',
      company: 'Himpunan Psikologi Indonesia (HIMPSI)',
      period: 'Agu 2024 – Des 2024',
      location: 'Kota Tangerang',
      type: 'Sukarelawan',
      highlights: [
        'Bikin platform pendaftaran terintegrasi di Google Sites',
        'Buat sistem e-voting buat keputusan organisasi',
        'Ngurusin fotografi dan dokumentasi acara',
      ],
      color: '#10b981',
    },
  ],
  zh: [
    {
      role: '平面设计师',
      company: 'Star Champs Indonesia',
      period: '2025年7月 – 至今',
      location: '坦格朗',
      type: '全职',
      highlights: [
        '为品牌推广和营销活动创作了200多个数字和平面设计',
        '一年内使社交媒体的粉丝和互动增长了200%',
        '通过Meta Business Suite管理数字营销活动',
        '主导了"希望之旅"研讨会（100多名参与者）',
        '开发了TheraCare——综合治疗中心信息系统',
      ],
      color: '#6366f1',
    },
    {
      role: '专员 / 创始人',
      company: 'Sagara Karya Kreanusati',
      period: '2024年1月 – 2026年7月',
      location: '印度尼西亚',
      type: '创意机构',
      highlights: [
        '涵盖广告、活动和技术的多学科创意机构',
        '致力于激发整个群岛的创造力',
      ],
      color: '#8b5cf6',
    },
    {
      role: '云计算学员',
      company: 'Bangkit Academy',
      period: '2024年9月 – 2025年1月',
      location: '雅加达',
      type: '培训',
      highlights: [
        '学习谷歌云平台（计算引擎、云存储、应用引擎）',
        '云基础设施、无服务器计算、部署流水线',
        '与机器学习和移动开发学员进行跨学科团队合作',
      ],
      color: '#38bdf8',
    },
    {
      role: '平面设计与视频剪辑师',
      company: '自由职业 (Fastwork.co)',
      period: '2023年9月 – 2025年1月',
      location: '南坦格朗',
      type: '自由职业',
      highlights: [
        '品牌识别、营销材料、数字内容制作 (Canva)',
        '宣传视频、社交媒体短片及企业宣传材料制作 (CapCut)',
      ],
      color: '#f59e0b',
    },
    {
      role: '信息系统协调员',
      company: '印度尼西亚心理学协会 (HIMPSI)',
      period: '2024年8月 – 2024年12月',
      location: '坦格朗市',
      type: '志愿者',
      highlights: [
        '在Google Sites上构建了集成的注册平台',
        '创建了用于组织治理决策的电子投票系统',
        '负责活动的摄影与记录',
      ],
      color: '#10b981',
    },
  ]
}

export const EDUCATION = {
  en: [
    { school: 'School of Technopreneur Nusantara', degree: 'S.Kom, Information System', period: '2022 – 2026' },
    { school: 'SMK Negeri 10 Kab. Tangerang', degree: 'Intermedia / Multimedia', period: 'Jun 2019 – Aug 2022' },
  ],
  id: [
    { school: 'School of Technopreneur Nusantara', degree: 'S.Kom, Sistem Informasi', period: '2022 – 2026' },
    { school: 'SMK Negeri 10 Kab. Tangerang', degree: 'Multimedia', period: 'Jun 2019 – Agu 2022' },
  ],
  zh: [
    { school: 'Nusantara科技创业学院', degree: '学士，信息系统', period: '2022 – 2026' },
    { school: '坦格朗第10职业高中', degree: '多媒体', period: '2019年6月 – 2022年8月' },
  ]
}

export const PROJECTS = {
  en: [
    {
      id: 'p1',
      name: 'TheraCare Information System',
      description: 'An integrated therapy center information system designed to streamline patient registration, scheduling, and medical records management.',
      category: 'Web Development',
      tags: ['HTML', 'System Design', 'Project Management'],
      link: '#',
      image: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&q=80&w=800',
      color: '#10b981',
    },
    {
      id: 'p2',
      name: '"The Journey of Hope" Seminar',
      description: 'Lead organizer for a massive seminar with 100+ participants. Handled end-to-end event management, branding, and promotional materials.',
      category: 'Event Organizer',
      tags: ['Leadership', 'Event Planning', 'Public Speaking'],
      link: '#',
      image: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&q=80&w=800',
      color: '#8b5cf6',
    },
    {
      id: 'p3',
      name: 'Star Champs Digital Campaigns',
      description: 'Designed over 200+ digital and print materials for marketing campaigns. Increased social media engagement and follower growth by 200%.',
      category: 'Graphic Design',
      tags: ['Canva', 'Meta Business Suite', 'Social Media'],
      link: '#',
      image: 'https://images.unsplash.com/photo-1626785774573-4b799315345d?auto=format&fit=crop&q=80&w=800',
      color: '#f59e0b',
    },
    {
      id: 'p4',
      name: 'GCP Scalable Web Architecture',
      description: 'Architected and deployed a highly available web application infrastructure using Google Cloud Platform load balancers and compute engines.',
      category: 'Cloud Computing',
      tags: ['GCP', 'Load Balancing', 'Infrastructure'],
      link: '#',
      image: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&q=80&w=800',
      color: '#38bdf8',
    },
    {
      id: 'p5',
      name: 'HIMPSI E-Voting System',
      description: 'Developed an integrated e-voting system and registration platform for organizational governance decisions and event management.',
      category: 'Web Development',
      tags: ['Google Sites', 'Data Management'],
      link: '#',
      image: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&q=80&w=800',
      color: '#ef4444',
    },
    {
      id: 'p6',
      name: 'Corporate Branding Videos',
      description: 'Freelance video editing projects for corporate clients and SME promotional campaigns, delivering high-retention video content.',
      category: 'Video Editing',
      tags: ['CapCut', 'Storytelling', 'Motion Graphics'],
      link: '#',
      image: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?auto=format&fit=crop&q=80&w=800',
      color: '#ec4899',
    },
  ],
  id: [
    {
      id: 'p1',
      name: 'Sistem Informasi TheraCare',
      description: 'Sistem informasi pusat terapi terintegrasi, dirancang untuk mempermudah pendaftaran pasien, penjadwalan, dan rekam medis.',
      category: 'Web Development',
      tags: ['HTML', 'System Design', 'Project Management'],
      link: '#',
      image: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&q=80&w=800',
      color: '#10b981',
    },
    {
      id: 'p2',
      name: 'Seminar "The Journey of Hope"',
      description: 'Jadi ketua panitia untuk seminar besar dengan 100+ peserta. Ngurusin semuanya dari awal sampai akhir, mulai dari branding sampai materi promosi.',
      category: 'Event Organizer',
      tags: ['Leadership', 'Event Planning', 'Public Speaking'],
      link: '#',
      image: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&q=80&w=800',
      color: '#8b5cf6',
    },
    {
      id: 'p3',
      name: 'Kampanye Digital Star Champs',
      description: 'Bikin lebih dari 200 desain digital & cetak buat kampanye marketing. Sukses naikin engagement dan jumlah followers sosmed sampai 200%.',
      category: 'Graphic Design',
      tags: ['Canva', 'Meta Business Suite', 'Social Media'],
      link: '#',
      image: 'https://images.unsplash.com/photo-1626785774573-4b799315345d?auto=format&fit=crop&q=80&w=800',
      color: '#f59e0b',
    },
    {
      id: 'p4',
      name: 'Arsitektur Web Scalable GCP',
      description: 'Merancang dan nge-deploy infrastruktur aplikasi web yang highly available pakai load balancer dan compute engine dari Google Cloud Platform.',
      category: 'Cloud Computing',
      tags: ['GCP', 'Load Balancing', 'Infrastructure'],
      link: '#',
      image: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&q=80&w=800',
      color: '#38bdf8',
    },
    {
      id: 'p5',
      name: 'Sistem E-Voting HIMPSI',
      description: 'Bikin sistem e-voting dan platform pendaftaran yang terintegrasi buat bantu pengambilan keputusan organisasi dan manajemen acara.',
      category: 'Web Development',
      tags: ['Google Sites', 'Data Management'],
      link: '#',
      image: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&q=80&w=800',
      color: '#ef4444',
    },
    {
      id: 'p6',
      name: 'Video Branding Perusahaan',
      description: 'Proyek freelance ngedit video buat klien perusahaan dan kampanye promosi UMKM, nyediain konten video dengan retensi tinggi.',
      category: 'Video Editing',
      tags: ['CapCut', 'Storytelling', 'Motion Graphics'],
      link: '#',
      image: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?auto=format&fit=crop&q=80&w=800',
      color: '#ec4899',
    },
  ],
  zh: [
    {
      id: 'p1',
      name: 'TheraCare 信息系统',
      description: '一个综合治疗中心信息系统，旨在简化患者注册、日程安排和医疗记录管理。',
      category: 'Web开发',
      tags: ['HTML', '系统设计', '项目管理'],
      link: '#',
      image: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&q=80&w=800',
      color: '#10b981',
    },
    {
      id: 'p2',
      name: '"希望之旅"研讨会',
      description: '担任100多人大型研讨会的首席组织者。处理了端到端的活动管理、品牌推广和宣传材料。',
      category: '活动组织',
      tags: ['领导力', '活动策划', '公开演讲'],
      link: '#',
      image: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&q=80&w=800',
      color: '#8b5cf6',
    },
    {
      id: 'p3',
      name: 'Star Champs 数字营销',
      description: '为营销活动设计了200多份数字和印刷材料。将社交媒体的互动和粉丝增长提高了200%。',
      category: '平面设计',
      tags: ['Canva', 'Meta Business Suite', '社交媒体'],
      link: '#',
      image: 'https://images.unsplash.com/photo-1626785774573-4b799315345d?auto=format&fit=crop&q=80&w=800',
      color: '#f59e0b',
    },
    {
      id: 'p4',
      name: 'GCP 可扩展Web架构',
      description: '使用谷歌云平台的负载均衡器和计算引擎，构建并部署了高可用性的Web应用基础设施。',
      category: '云计算',
      tags: ['GCP', '负载均衡', '基础设施'],
      link: '#',
      image: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&q=80&w=800',
      color: '#38bdf8',
    },
    {
      id: 'p5',
      name: 'HIMPSI 电子投票系统',
      description: '开发了集成的电子投票系统和注册平台，用于组织治理决策和活动管理。',
      category: 'Web开发',
      tags: ['Google Sites', '数据管理'],
      link: '#',
      image: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&q=80&w=800',
      color: '#ef4444',
    },
    {
      id: 'p6',
      name: '企业品牌宣传视频',
      description: '为企业客户和中小企业推广活动提供视频剪辑自由职业服务，交付高留存率的视频内容。',
      category: '视频剪辑',
      tags: ['CapCut', '讲故事', '动态图形'],
      link: '#',
      image: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?auto=format&fit=crop&q=80&w=800',
      color: '#ec4899',
    },
  ]
}
